server:
  port: 8080
  
---
spring:
  profiles: local-mssql
  datasource:
    url: jdbc:mysql://us-cdbr-iron-east-04.cleardb.net/ad_f33ba6ada231ff9?user=ba97973a969749&password=99ad927b
    username: ba97973a969749
    password: 99ad927b
    port: 3306
  
---
server:
  context-path: /
---
spring:
  jpa:
    properties:
      hibernate.dialect:
        org.hibernate.dialect.MySQL5Dialect
---
spring:
  datasource:
    url:
      mysql://ba97973a969749:99ad927b@us-cdbr-iron-east-04.cleardb.net:3306/ad_f33ba6ada231ff9?reconnect=true

