server:
  port: 8080
  
---
spring:
  profiles: local-mssql
  datasource:
    url: jdbc:mysql://us-cdbr-iron-east-04.cleardb.net/ad_66a66cdd04b38e1?user=b767ff937a70e2&password=15d3196a
    username: b767ff937a70e2
    password: 15d3196a
    port: 3306
  
---
server:
  context-path: /
---
spring:
  jpa:
    properties:
      hibernate.dialect:
        org.hibernate.dialect.MySQL5Dialect
---
spring:
  datasource:
    url:
      mysql://b767ff937a70e2:15d3196a@us-cdbr-iron-east-04.cleardb.net:3306/ad_66a66cdd04b38e1?reconnect=true

