server:
  port: 8080
  
---
spring:
  profiles: local-mssql
  datasource:
<<<<<<< HEAD
    url: jdbc:mysql://localhost:3306/ad_f33ba6ada231ff9?useSSL=false&user=root&password=root
=======
    url: jdbc:mysql://localhost:3306/aviation?useSSL=false&user=root&password=root
>>>>>>> branch 'master' of https://github.com/cglean/performance-component-analysis/
    username: root
    password: root
    dbcp:
      max-active: 5
    tomcat:
      max-active: 5
 
---
server:
  context-path: /
---
spring:
  jpa:
    properties:
      hibernate.dialect:
        org.hibernate.dialect.PostgreSQLDialect
---
spring:
  datasource:
    url:
<<<<<<< HEAD
      jdbc:mysql://localhost:3306/ad_f33ba6ada231ff9?useSSL=false&user=root&password=root
=======
      jdbc:mysql://localhost:3306/aviation?useSSL=false&user=root&password=root
>>>>>>> branch 'master' of https://github.com/cglean/performance-component-analysis/
