server:
  port: 8080
  
---
spring:
  profiles: local-mssql
  datasource:
    url: jdbc:mysql://us-cdbr-iron-east-04.cleardb.net/ad_01711bd994f900d?user=b6c7bda2e506a1&password=12987fa9
    username: b6c7bda2e506a1
    password: 12987fa9
    dbcp:
      max-active: 5
    tomcat:
      max-active: 5
 
---
server:
  context-path: /
---
spring:
  jpa:
    properties:
      hibernate.dialect:
        org.hibernate.dialect.MySQL5Dialect
---
spring:
  datasource:
    url:
      jdbc:mysql://us-cdbr-iron-east-04.cleardb.net/ad_01711bd994f900d?user=b6c7bda2e506a1&password=12987fa9
